### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by dsiminiuk** [lupus78/feedtransmission#1]
I have this working, and frankly it's the only thing I've been able to get working that does exactly what I want.

One issue I have is I want to log all activity to files named for each day. The python "print" statements output to the console and cannot be redirected to files (as far as I can tell).

Could you implement writing all activity to STDOUT, or allow a logfile argument to be passed in with a flag, or just write output to any file, or some other method of allowing redirect of STDOUT to a file?

Currently I've commented out the print statements for the successful actions and only print on errors. Running from cron, I'll be notified of the errors only (desirable).

Thanks

**Comment by lupus78** [comment]
Good idea and I'm happy you like my little code :)

I have just pushed some changes, implemented simple logging.
`--log-file` argument can be used to specify a filename, otherwise everything is printed to output.

It still not make difference between errors and the add torrent message, all goes into 1 file.

**Comment by dsiminiuk** [comment]
Outstanding! It works, you rock.
