### ISSUE TITLE
urllib2.HTTPError

### ISSUE THREAD

**Issue by accessone67** [lupus78/feedtransmission#3]
When running the script it always gives me error

`[INFO]: Adding Torrent: XXXXXXXXXXXXX to /media/.....
[ERROR]: Error adding item 'http://www.xxx/xxx.torrent': <class 'urllib2.HTTPError'>
`

**Comment by lupus78** [comment]
What's the actual link you are trying to request?

**Comment by erenard** [comment]
Hey, I had a similar error, it was due to an HTTPS torrent link.
The lib **transmissionrpc** has an [open bug](https://bitbucket.org/blueluna/transmissionrpc/issues/84/urllib2httperror-http-error-403-forbidden) about adding an https torrent link.

I patched the transmissionrpc lib localy and everything started working fine. That being said, it would help if your code logged more info about the HTTPError.

You could work around the bug by downloading the torrent file and passing it to add_torrent() with a 'file://' type URI.

Cheers.

**Comment by lupus78** [comment]
Thanks @Tony763 for the PR, however I have modified it a bit, and introduced a --download-with-python argument. Check the Readme for details.
